# Installed by icons-humbleicons — discovered as /usr/share/iconlibutils/library/humbleicons/
name=humbleicons
type=auto
path=/usr/share/icons-humbleicons
title=humbleicons
license=MIT
homepage=https://humbleicons.com/
description=Humbleicons
package=icons-humbleicons
